services:
  server:
    build: ./backend/
    ports:
      - 8080:8080
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
  
  front:
    build: ./frontend
    ports:
      - 3000:3000
    